/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "messenger_constants.h"

namespace thrift_gen_messenger {

const messengerConstants g_messenger_constants;

messengerConstants::messengerConstants() {
}

} // namespace

