/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TransferService_H
#define TransferService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "messenger_types.h"

namespace thrift_gen_messenger {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TransferServiceIf {
 public:
  virtual ~TransferServiceIf() {}
  virtual void writeMessage(std::string& _return, const Message& _v) = 0;
  virtual void writeBool(std::string& _return, const std::string& _id, const bool _v) = 0;
  virtual void writeI16(std::string& _return, const std::string& _id, const int16_t _v) = 0;
  virtual void writeI32(std::string& _return, const std::string& _id, const int32_t _v) = 0;
  virtual void writeI64(std::string& _return, const std::string& _id, const int64_t _v) = 0;
  virtual void writeDouble(std::string& _return, const std::string& _id, const double _v) = 0;
  virtual void writeString(std::string& _return, const std::string& _id, const std::string& _v) = 0;
  virtual void readMessage(Message& _return, const std::string& _id) = 0;
  virtual bool readBool(const std::string& _id) = 0;
  virtual int16_t readI16(const std::string& _id) = 0;
  virtual int32_t readI32(const std::string& _id) = 0;
  virtual int64_t readI64(const std::string& _id) = 0;
  virtual double readDouble(const std::string& _id) = 0;
  virtual void readString(std::string& _return, const std::string& _id) = 0;
  virtual bool writeId(const std::string& _id) = 0;
  virtual void readId(std::vector<std::string> & _return) = 0;
};

class TransferServiceIfFactory {
 public:
  typedef TransferServiceIf Handler;

  virtual ~TransferServiceIfFactory() {}

  virtual TransferServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TransferServiceIf* /* handler */) = 0;
};

class TransferServiceIfSingletonFactory : virtual public TransferServiceIfFactory {
 public:
  TransferServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf>& iface) : iface_(iface) {}
  virtual ~TransferServiceIfSingletonFactory() {}

  virtual TransferServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TransferServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface_;
};

class TransferServiceNull : virtual public TransferServiceIf {
 public:
  virtual ~TransferServiceNull() {}
  void writeMessage(std::string& /* _return */, const Message& /* _v */) {
    return;
  }
  void writeBool(std::string& /* _return */, const std::string& /* _id */, const bool /* _v */) {
    return;
  }
  void writeI16(std::string& /* _return */, const std::string& /* _id */, const int16_t /* _v */) {
    return;
  }
  void writeI32(std::string& /* _return */, const std::string& /* _id */, const int32_t /* _v */) {
    return;
  }
  void writeI64(std::string& /* _return */, const std::string& /* _id */, const int64_t /* _v */) {
    return;
  }
  void writeDouble(std::string& /* _return */, const std::string& /* _id */, const double /* _v */) {
    return;
  }
  void writeString(std::string& /* _return */, const std::string& /* _id */, const std::string& /* _v */) {
    return;
  }
  void readMessage(Message& /* _return */, const std::string& /* _id */) {
    return;
  }
  bool readBool(const std::string& /* _id */) {
    bool _return = false;
    return _return;
  }
  int16_t readI16(const std::string& /* _id */) {
    int16_t _return = 0;
    return _return;
  }
  int32_t readI32(const std::string& /* _id */) {
    int32_t _return = 0;
    return _return;
  }
  int64_t readI64(const std::string& /* _id */) {
    int64_t _return = 0;
    return _return;
  }
  double readDouble(const std::string& /* _id */) {
    double _return = (double)0;
    return _return;
  }
  void readString(std::string& /* _return */, const std::string& /* _id */) {
    return;
  }
  bool writeId(const std::string& /* _id */) {
    bool _return = false;
    return _return;
  }
  void readId(std::vector<std::string> & /* _return */) {
    return;
  }
};

typedef struct _TransferService_writeMessage_args__isset {
  _TransferService_writeMessage_args__isset() : _v(false) {}
  bool _v :1;
} _TransferService_writeMessage_args__isset;

class TransferService_writeMessage_args {
 public:

  TransferService_writeMessage_args(const TransferService_writeMessage_args&);
  TransferService_writeMessage_args& operator=(const TransferService_writeMessage_args&);
  TransferService_writeMessage_args() {
  }

  virtual ~TransferService_writeMessage_args() throw();
  Message _v;

  _TransferService_writeMessage_args__isset __isset;

  void __set__v(const Message& val);

  bool operator == (const TransferService_writeMessage_args & rhs) const
  {
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeMessage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeMessage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeMessage_pargs {
 public:


  virtual ~TransferService_writeMessage_pargs() throw();
  const Message* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeMessage_result__isset {
  _TransferService_writeMessage_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeMessage_result__isset;

class TransferService_writeMessage_result {
 public:

  TransferService_writeMessage_result(const TransferService_writeMessage_result&);
  TransferService_writeMessage_result& operator=(const TransferService_writeMessage_result&);
  TransferService_writeMessage_result() : success() {
  }

  virtual ~TransferService_writeMessage_result() throw();
  std::string success;

  _TransferService_writeMessage_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeMessage_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeMessage_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeMessage_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeMessage_presult__isset {
  _TransferService_writeMessage_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeMessage_presult__isset;

class TransferService_writeMessage_presult {
 public:


  virtual ~TransferService_writeMessage_presult() throw();
  std::string* success;

  _TransferService_writeMessage_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeBool_args__isset {
  _TransferService_writeBool_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeBool_args__isset;

class TransferService_writeBool_args {
 public:

  TransferService_writeBool_args(const TransferService_writeBool_args&);
  TransferService_writeBool_args& operator=(const TransferService_writeBool_args&);
  TransferService_writeBool_args() : _id(), _v(0) {
  }

  virtual ~TransferService_writeBool_args() throw();
  std::string _id;
  bool _v;

  _TransferService_writeBool_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const bool val);

  bool operator == (const TransferService_writeBool_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeBool_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeBool_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeBool_pargs {
 public:


  virtual ~TransferService_writeBool_pargs() throw();
  const std::string* _id;
  const bool* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeBool_result__isset {
  _TransferService_writeBool_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeBool_result__isset;

class TransferService_writeBool_result {
 public:

  TransferService_writeBool_result(const TransferService_writeBool_result&);
  TransferService_writeBool_result& operator=(const TransferService_writeBool_result&);
  TransferService_writeBool_result() : success() {
  }

  virtual ~TransferService_writeBool_result() throw();
  std::string success;

  _TransferService_writeBool_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeBool_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeBool_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeBool_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeBool_presult__isset {
  _TransferService_writeBool_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeBool_presult__isset;

class TransferService_writeBool_presult {
 public:


  virtual ~TransferService_writeBool_presult() throw();
  std::string* success;

  _TransferService_writeBool_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeI16_args__isset {
  _TransferService_writeI16_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeI16_args__isset;

class TransferService_writeI16_args {
 public:

  TransferService_writeI16_args(const TransferService_writeI16_args&);
  TransferService_writeI16_args& operator=(const TransferService_writeI16_args&);
  TransferService_writeI16_args() : _id(), _v(0) {
  }

  virtual ~TransferService_writeI16_args() throw();
  std::string _id;
  int16_t _v;

  _TransferService_writeI16_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const int16_t val);

  bool operator == (const TransferService_writeI16_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI16_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI16_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeI16_pargs {
 public:


  virtual ~TransferService_writeI16_pargs() throw();
  const std::string* _id;
  const int16_t* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI16_result__isset {
  _TransferService_writeI16_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI16_result__isset;

class TransferService_writeI16_result {
 public:

  TransferService_writeI16_result(const TransferService_writeI16_result&);
  TransferService_writeI16_result& operator=(const TransferService_writeI16_result&);
  TransferService_writeI16_result() : success() {
  }

  virtual ~TransferService_writeI16_result() throw();
  std::string success;

  _TransferService_writeI16_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeI16_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI16_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI16_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI16_presult__isset {
  _TransferService_writeI16_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI16_presult__isset;

class TransferService_writeI16_presult {
 public:


  virtual ~TransferService_writeI16_presult() throw();
  std::string* success;

  _TransferService_writeI16_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeI32_args__isset {
  _TransferService_writeI32_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeI32_args__isset;

class TransferService_writeI32_args {
 public:

  TransferService_writeI32_args(const TransferService_writeI32_args&);
  TransferService_writeI32_args& operator=(const TransferService_writeI32_args&);
  TransferService_writeI32_args() : _id(), _v(0) {
  }

  virtual ~TransferService_writeI32_args() throw();
  std::string _id;
  int32_t _v;

  _TransferService_writeI32_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const int32_t val);

  bool operator == (const TransferService_writeI32_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI32_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI32_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeI32_pargs {
 public:


  virtual ~TransferService_writeI32_pargs() throw();
  const std::string* _id;
  const int32_t* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI32_result__isset {
  _TransferService_writeI32_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI32_result__isset;

class TransferService_writeI32_result {
 public:

  TransferService_writeI32_result(const TransferService_writeI32_result&);
  TransferService_writeI32_result& operator=(const TransferService_writeI32_result&);
  TransferService_writeI32_result() : success() {
  }

  virtual ~TransferService_writeI32_result() throw();
  std::string success;

  _TransferService_writeI32_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeI32_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI32_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI32_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI32_presult__isset {
  _TransferService_writeI32_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI32_presult__isset;

class TransferService_writeI32_presult {
 public:


  virtual ~TransferService_writeI32_presult() throw();
  std::string* success;

  _TransferService_writeI32_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeI64_args__isset {
  _TransferService_writeI64_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeI64_args__isset;

class TransferService_writeI64_args {
 public:

  TransferService_writeI64_args(const TransferService_writeI64_args&);
  TransferService_writeI64_args& operator=(const TransferService_writeI64_args&);
  TransferService_writeI64_args() : _id(), _v(0) {
  }

  virtual ~TransferService_writeI64_args() throw();
  std::string _id;
  int64_t _v;

  _TransferService_writeI64_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const int64_t val);

  bool operator == (const TransferService_writeI64_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI64_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI64_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeI64_pargs {
 public:


  virtual ~TransferService_writeI64_pargs() throw();
  const std::string* _id;
  const int64_t* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI64_result__isset {
  _TransferService_writeI64_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI64_result__isset;

class TransferService_writeI64_result {
 public:

  TransferService_writeI64_result(const TransferService_writeI64_result&);
  TransferService_writeI64_result& operator=(const TransferService_writeI64_result&);
  TransferService_writeI64_result() : success() {
  }

  virtual ~TransferService_writeI64_result() throw();
  std::string success;

  _TransferService_writeI64_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeI64_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeI64_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeI64_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeI64_presult__isset {
  _TransferService_writeI64_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeI64_presult__isset;

class TransferService_writeI64_presult {
 public:


  virtual ~TransferService_writeI64_presult() throw();
  std::string* success;

  _TransferService_writeI64_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeDouble_args__isset {
  _TransferService_writeDouble_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeDouble_args__isset;

class TransferService_writeDouble_args {
 public:

  TransferService_writeDouble_args(const TransferService_writeDouble_args&);
  TransferService_writeDouble_args& operator=(const TransferService_writeDouble_args&);
  TransferService_writeDouble_args() : _id(), _v(0) {
  }

  virtual ~TransferService_writeDouble_args() throw();
  std::string _id;
  double _v;

  _TransferService_writeDouble_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const double val);

  bool operator == (const TransferService_writeDouble_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeDouble_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeDouble_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeDouble_pargs {
 public:


  virtual ~TransferService_writeDouble_pargs() throw();
  const std::string* _id;
  const double* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeDouble_result__isset {
  _TransferService_writeDouble_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeDouble_result__isset;

class TransferService_writeDouble_result {
 public:

  TransferService_writeDouble_result(const TransferService_writeDouble_result&);
  TransferService_writeDouble_result& operator=(const TransferService_writeDouble_result&);
  TransferService_writeDouble_result() : success() {
  }

  virtual ~TransferService_writeDouble_result() throw();
  std::string success;

  _TransferService_writeDouble_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeDouble_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeDouble_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeDouble_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeDouble_presult__isset {
  _TransferService_writeDouble_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeDouble_presult__isset;

class TransferService_writeDouble_presult {
 public:


  virtual ~TransferService_writeDouble_presult() throw();
  std::string* success;

  _TransferService_writeDouble_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeString_args__isset {
  _TransferService_writeString_args__isset() : _id(false), _v(false) {}
  bool _id :1;
  bool _v :1;
} _TransferService_writeString_args__isset;

class TransferService_writeString_args {
 public:

  TransferService_writeString_args(const TransferService_writeString_args&);
  TransferService_writeString_args& operator=(const TransferService_writeString_args&);
  TransferService_writeString_args() : _id(), _v() {
  }

  virtual ~TransferService_writeString_args() throw();
  std::string _id;
  std::string _v;

  _TransferService_writeString_args__isset __isset;

  void __set__id(const std::string& val);

  void __set__v(const std::string& val);

  bool operator == (const TransferService_writeString_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    if (!(_v == rhs._v))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeString_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeString_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeString_pargs {
 public:


  virtual ~TransferService_writeString_pargs() throw();
  const std::string* _id;
  const std::string* _v;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeString_result__isset {
  _TransferService_writeString_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeString_result__isset;

class TransferService_writeString_result {
 public:

  TransferService_writeString_result(const TransferService_writeString_result&);
  TransferService_writeString_result& operator=(const TransferService_writeString_result&);
  TransferService_writeString_result() : success() {
  }

  virtual ~TransferService_writeString_result() throw();
  std::string success;

  _TransferService_writeString_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_writeString_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeString_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeString_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeString_presult__isset {
  _TransferService_writeString_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeString_presult__isset;

class TransferService_writeString_presult {
 public:


  virtual ~TransferService_writeString_presult() throw();
  std::string* success;

  _TransferService_writeString_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readMessage_args__isset {
  _TransferService_readMessage_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readMessage_args__isset;

class TransferService_readMessage_args {
 public:

  TransferService_readMessage_args(const TransferService_readMessage_args&);
  TransferService_readMessage_args& operator=(const TransferService_readMessage_args&);
  TransferService_readMessage_args() : _id() {
  }

  virtual ~TransferService_readMessage_args() throw();
  std::string _id;

  _TransferService_readMessage_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readMessage_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readMessage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readMessage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readMessage_pargs {
 public:


  virtual ~TransferService_readMessage_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readMessage_result__isset {
  _TransferService_readMessage_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readMessage_result__isset;

class TransferService_readMessage_result {
 public:

  TransferService_readMessage_result(const TransferService_readMessage_result&);
  TransferService_readMessage_result& operator=(const TransferService_readMessage_result&);
  TransferService_readMessage_result() {
  }

  virtual ~TransferService_readMessage_result() throw();
  Message success;

  _TransferService_readMessage_result__isset __isset;

  void __set_success(const Message& val);

  bool operator == (const TransferService_readMessage_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readMessage_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readMessage_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readMessage_presult__isset {
  _TransferService_readMessage_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readMessage_presult__isset;

class TransferService_readMessage_presult {
 public:


  virtual ~TransferService_readMessage_presult() throw();
  Message* success;

  _TransferService_readMessage_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readBool_args__isset {
  _TransferService_readBool_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readBool_args__isset;

class TransferService_readBool_args {
 public:

  TransferService_readBool_args(const TransferService_readBool_args&);
  TransferService_readBool_args& operator=(const TransferService_readBool_args&);
  TransferService_readBool_args() : _id() {
  }

  virtual ~TransferService_readBool_args() throw();
  std::string _id;

  _TransferService_readBool_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readBool_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readBool_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readBool_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readBool_pargs {
 public:


  virtual ~TransferService_readBool_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readBool_result__isset {
  _TransferService_readBool_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readBool_result__isset;

class TransferService_readBool_result {
 public:

  TransferService_readBool_result(const TransferService_readBool_result&);
  TransferService_readBool_result& operator=(const TransferService_readBool_result&);
  TransferService_readBool_result() : success(0) {
  }

  virtual ~TransferService_readBool_result() throw();
  bool success;

  _TransferService_readBool_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const TransferService_readBool_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readBool_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readBool_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readBool_presult__isset {
  _TransferService_readBool_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readBool_presult__isset;

class TransferService_readBool_presult {
 public:


  virtual ~TransferService_readBool_presult() throw();
  bool* success;

  _TransferService_readBool_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readI16_args__isset {
  _TransferService_readI16_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readI16_args__isset;

class TransferService_readI16_args {
 public:

  TransferService_readI16_args(const TransferService_readI16_args&);
  TransferService_readI16_args& operator=(const TransferService_readI16_args&);
  TransferService_readI16_args() : _id() {
  }

  virtual ~TransferService_readI16_args() throw();
  std::string _id;

  _TransferService_readI16_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readI16_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI16_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI16_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readI16_pargs {
 public:


  virtual ~TransferService_readI16_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI16_result__isset {
  _TransferService_readI16_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readI16_result__isset;

class TransferService_readI16_result {
 public:

  TransferService_readI16_result(const TransferService_readI16_result&);
  TransferService_readI16_result& operator=(const TransferService_readI16_result&);
  TransferService_readI16_result() : success(0) {
  }

  virtual ~TransferService_readI16_result() throw();
  int16_t success;

  _TransferService_readI16_result__isset __isset;

  void __set_success(const int16_t val);

  bool operator == (const TransferService_readI16_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI16_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI16_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI16_presult__isset {
  _TransferService_readI16_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readI16_presult__isset;

class TransferService_readI16_presult {
 public:


  virtual ~TransferService_readI16_presult() throw();
  int16_t* success;

  _TransferService_readI16_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readI32_args__isset {
  _TransferService_readI32_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readI32_args__isset;

class TransferService_readI32_args {
 public:

  TransferService_readI32_args(const TransferService_readI32_args&);
  TransferService_readI32_args& operator=(const TransferService_readI32_args&);
  TransferService_readI32_args() : _id() {
  }

  virtual ~TransferService_readI32_args() throw();
  std::string _id;

  _TransferService_readI32_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readI32_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI32_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI32_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readI32_pargs {
 public:


  virtual ~TransferService_readI32_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI32_result__isset {
  _TransferService_readI32_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readI32_result__isset;

class TransferService_readI32_result {
 public:

  TransferService_readI32_result(const TransferService_readI32_result&);
  TransferService_readI32_result& operator=(const TransferService_readI32_result&);
  TransferService_readI32_result() : success(0) {
  }

  virtual ~TransferService_readI32_result() throw();
  int32_t success;

  _TransferService_readI32_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const TransferService_readI32_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI32_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI32_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI32_presult__isset {
  _TransferService_readI32_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readI32_presult__isset;

class TransferService_readI32_presult {
 public:


  virtual ~TransferService_readI32_presult() throw();
  int32_t* success;

  _TransferService_readI32_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readI64_args__isset {
  _TransferService_readI64_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readI64_args__isset;

class TransferService_readI64_args {
 public:

  TransferService_readI64_args(const TransferService_readI64_args&);
  TransferService_readI64_args& operator=(const TransferService_readI64_args&);
  TransferService_readI64_args() : _id() {
  }

  virtual ~TransferService_readI64_args() throw();
  std::string _id;

  _TransferService_readI64_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readI64_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI64_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI64_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readI64_pargs {
 public:


  virtual ~TransferService_readI64_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI64_result__isset {
  _TransferService_readI64_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readI64_result__isset;

class TransferService_readI64_result {
 public:

  TransferService_readI64_result(const TransferService_readI64_result&);
  TransferService_readI64_result& operator=(const TransferService_readI64_result&);
  TransferService_readI64_result() : success(0) {
  }

  virtual ~TransferService_readI64_result() throw();
  int64_t success;

  _TransferService_readI64_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const TransferService_readI64_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readI64_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readI64_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readI64_presult__isset {
  _TransferService_readI64_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readI64_presult__isset;

class TransferService_readI64_presult {
 public:


  virtual ~TransferService_readI64_presult() throw();
  int64_t* success;

  _TransferService_readI64_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readDouble_args__isset {
  _TransferService_readDouble_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readDouble_args__isset;

class TransferService_readDouble_args {
 public:

  TransferService_readDouble_args(const TransferService_readDouble_args&);
  TransferService_readDouble_args& operator=(const TransferService_readDouble_args&);
  TransferService_readDouble_args() : _id() {
  }

  virtual ~TransferService_readDouble_args() throw();
  std::string _id;

  _TransferService_readDouble_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readDouble_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readDouble_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readDouble_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readDouble_pargs {
 public:


  virtual ~TransferService_readDouble_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readDouble_result__isset {
  _TransferService_readDouble_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readDouble_result__isset;

class TransferService_readDouble_result {
 public:

  TransferService_readDouble_result(const TransferService_readDouble_result&);
  TransferService_readDouble_result& operator=(const TransferService_readDouble_result&);
  TransferService_readDouble_result() : success(0) {
  }

  virtual ~TransferService_readDouble_result() throw();
  double success;

  _TransferService_readDouble_result__isset __isset;

  void __set_success(const double val);

  bool operator == (const TransferService_readDouble_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readDouble_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readDouble_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readDouble_presult__isset {
  _TransferService_readDouble_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readDouble_presult__isset;

class TransferService_readDouble_presult {
 public:


  virtual ~TransferService_readDouble_presult() throw();
  double* success;

  _TransferService_readDouble_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_readString_args__isset {
  _TransferService_readString_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_readString_args__isset;

class TransferService_readString_args {
 public:

  TransferService_readString_args(const TransferService_readString_args&);
  TransferService_readString_args& operator=(const TransferService_readString_args&);
  TransferService_readString_args() : _id() {
  }

  virtual ~TransferService_readString_args() throw();
  std::string _id;

  _TransferService_readString_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_readString_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_readString_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readString_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readString_pargs {
 public:


  virtual ~TransferService_readString_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readString_result__isset {
  _TransferService_readString_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readString_result__isset;

class TransferService_readString_result {
 public:

  TransferService_readString_result(const TransferService_readString_result&);
  TransferService_readString_result& operator=(const TransferService_readString_result&);
  TransferService_readString_result() : success() {
  }

  virtual ~TransferService_readString_result() throw();
  std::string success;

  _TransferService_readString_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_readString_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readString_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readString_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readString_presult__isset {
  _TransferService_readString_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readString_presult__isset;

class TransferService_readString_presult {
 public:


  virtual ~TransferService_readString_presult() throw();
  std::string* success;

  _TransferService_readString_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TransferService_writeId_args__isset {
  _TransferService_writeId_args__isset() : _id(false) {}
  bool _id :1;
} _TransferService_writeId_args__isset;

class TransferService_writeId_args {
 public:

  TransferService_writeId_args(const TransferService_writeId_args&);
  TransferService_writeId_args& operator=(const TransferService_writeId_args&);
  TransferService_writeId_args() : _id() {
  }

  virtual ~TransferService_writeId_args() throw();
  std::string _id;

  _TransferService_writeId_args__isset __isset;

  void __set__id(const std::string& val);

  bool operator == (const TransferService_writeId_args & rhs) const
  {
    if (!(_id == rhs._id))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeId_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeId_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_writeId_pargs {
 public:


  virtual ~TransferService_writeId_pargs() throw();
  const std::string* _id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeId_result__isset {
  _TransferService_writeId_result__isset() : success(false) {}
  bool success :1;
} _TransferService_writeId_result__isset;

class TransferService_writeId_result {
 public:

  TransferService_writeId_result(const TransferService_writeId_result&);
  TransferService_writeId_result& operator=(const TransferService_writeId_result&);
  TransferService_writeId_result() : success(0) {
  }

  virtual ~TransferService_writeId_result() throw();
  bool success;

  _TransferService_writeId_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const TransferService_writeId_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_writeId_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_writeId_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_writeId_presult__isset {
  _TransferService_writeId_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_writeId_presult__isset;

class TransferService_writeId_presult {
 public:


  virtual ~TransferService_writeId_presult() throw();
  bool* success;

  _TransferService_writeId_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class TransferService_readId_args {
 public:

  TransferService_readId_args(const TransferService_readId_args&);
  TransferService_readId_args& operator=(const TransferService_readId_args&);
  TransferService_readId_args() {
  }

  virtual ~TransferService_readId_args() throw();

  bool operator == (const TransferService_readId_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const TransferService_readId_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readId_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_readId_pargs {
 public:


  virtual ~TransferService_readId_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readId_result__isset {
  _TransferService_readId_result__isset() : success(false) {}
  bool success :1;
} _TransferService_readId_result__isset;

class TransferService_readId_result {
 public:

  TransferService_readId_result(const TransferService_readId_result&);
  TransferService_readId_result& operator=(const TransferService_readId_result&);
  TransferService_readId_result() {
  }

  virtual ~TransferService_readId_result() throw();
  std::vector<std::string>  success;

  _TransferService_readId_result__isset __isset;

  void __set_success(const std::vector<std::string> & val);

  bool operator == (const TransferService_readId_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_readId_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_readId_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_readId_presult__isset {
  _TransferService_readId_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_readId_presult__isset;

class TransferService_readId_presult {
 public:


  virtual ~TransferService_readId_presult() throw();
  std::vector<std::string> * success;

  _TransferService_readId_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TransferServiceClient : virtual public TransferServiceIf {
 public:
  TransferServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TransferServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void writeMessage(std::string& _return, const Message& _v);
  void send_writeMessage(const Message& _v);
  void recv_writeMessage(std::string& _return);
  void writeBool(std::string& _return, const std::string& _id, const bool _v);
  void send_writeBool(const std::string& _id, const bool _v);
  void recv_writeBool(std::string& _return);
  void writeI16(std::string& _return, const std::string& _id, const int16_t _v);
  void send_writeI16(const std::string& _id, const int16_t _v);
  void recv_writeI16(std::string& _return);
  void writeI32(std::string& _return, const std::string& _id, const int32_t _v);
  void send_writeI32(const std::string& _id, const int32_t _v);
  void recv_writeI32(std::string& _return);
  void writeI64(std::string& _return, const std::string& _id, const int64_t _v);
  void send_writeI64(const std::string& _id, const int64_t _v);
  void recv_writeI64(std::string& _return);
  void writeDouble(std::string& _return, const std::string& _id, const double _v);
  void send_writeDouble(const std::string& _id, const double _v);
  void recv_writeDouble(std::string& _return);
  void writeString(std::string& _return, const std::string& _id, const std::string& _v);
  void send_writeString(const std::string& _id, const std::string& _v);
  void recv_writeString(std::string& _return);
  void readMessage(Message& _return, const std::string& _id);
  void send_readMessage(const std::string& _id);
  void recv_readMessage(Message& _return);
  bool readBool(const std::string& _id);
  void send_readBool(const std::string& _id);
  bool recv_readBool();
  int16_t readI16(const std::string& _id);
  void send_readI16(const std::string& _id);
  int16_t recv_readI16();
  int32_t readI32(const std::string& _id);
  void send_readI32(const std::string& _id);
  int32_t recv_readI32();
  int64_t readI64(const std::string& _id);
  void send_readI64(const std::string& _id);
  int64_t recv_readI64();
  double readDouble(const std::string& _id);
  void send_readDouble(const std::string& _id);
  double recv_readDouble();
  void readString(std::string& _return, const std::string& _id);
  void send_readString(const std::string& _id);
  void recv_readString(std::string& _return);
  bool writeId(const std::string& _id);
  void send_writeId(const std::string& _id);
  bool recv_writeId();
  void readId(std::vector<std::string> & _return);
  void send_readId();
  void recv_readId(std::vector<std::string> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TransferServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TransferServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_writeMessage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeBool(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeI16(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeI32(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeI64(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeDouble(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeString(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readMessage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readBool(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readI16(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readI32(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readI64(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readDouble(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readString(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_writeId(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_readId(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TransferServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface) :
    iface_(iface) {
    processMap_["writeMessage"] = &TransferServiceProcessor::process_writeMessage;
    processMap_["writeBool"] = &TransferServiceProcessor::process_writeBool;
    processMap_["writeI16"] = &TransferServiceProcessor::process_writeI16;
    processMap_["writeI32"] = &TransferServiceProcessor::process_writeI32;
    processMap_["writeI64"] = &TransferServiceProcessor::process_writeI64;
    processMap_["writeDouble"] = &TransferServiceProcessor::process_writeDouble;
    processMap_["writeString"] = &TransferServiceProcessor::process_writeString;
    processMap_["readMessage"] = &TransferServiceProcessor::process_readMessage;
    processMap_["readBool"] = &TransferServiceProcessor::process_readBool;
    processMap_["readI16"] = &TransferServiceProcessor::process_readI16;
    processMap_["readI32"] = &TransferServiceProcessor::process_readI32;
    processMap_["readI64"] = &TransferServiceProcessor::process_readI64;
    processMap_["readDouble"] = &TransferServiceProcessor::process_readDouble;
    processMap_["readString"] = &TransferServiceProcessor::process_readString;
    processMap_["writeId"] = &TransferServiceProcessor::process_writeId;
    processMap_["readId"] = &TransferServiceProcessor::process_readId;
  }

  virtual ~TransferServiceProcessor() {}
};

class TransferServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TransferServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TransferServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TransferServiceIfFactory > handlerFactory_;
};

class TransferServiceMultiface : virtual public TransferServiceIf {
 public:
  TransferServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TransferServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TransferServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TransferServiceIf> > ifaces_;
  TransferServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void writeMessage(std::string& _return, const Message& _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeMessage(_return, _v);
    }
    ifaces_[i]->writeMessage(_return, _v);
    return;
  }

  void writeBool(std::string& _return, const std::string& _id, const bool _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeBool(_return, _id, _v);
    }
    ifaces_[i]->writeBool(_return, _id, _v);
    return;
  }

  void writeI16(std::string& _return, const std::string& _id, const int16_t _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeI16(_return, _id, _v);
    }
    ifaces_[i]->writeI16(_return, _id, _v);
    return;
  }

  void writeI32(std::string& _return, const std::string& _id, const int32_t _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeI32(_return, _id, _v);
    }
    ifaces_[i]->writeI32(_return, _id, _v);
    return;
  }

  void writeI64(std::string& _return, const std::string& _id, const int64_t _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeI64(_return, _id, _v);
    }
    ifaces_[i]->writeI64(_return, _id, _v);
    return;
  }

  void writeDouble(std::string& _return, const std::string& _id, const double _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeDouble(_return, _id, _v);
    }
    ifaces_[i]->writeDouble(_return, _id, _v);
    return;
  }

  void writeString(std::string& _return, const std::string& _id, const std::string& _v) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeString(_return, _id, _v);
    }
    ifaces_[i]->writeString(_return, _id, _v);
    return;
  }

  void readMessage(Message& _return, const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readMessage(_return, _id);
    }
    ifaces_[i]->readMessage(_return, _id);
    return;
  }

  bool readBool(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readBool(_id);
    }
    return ifaces_[i]->readBool(_id);
  }

  int16_t readI16(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readI16(_id);
    }
    return ifaces_[i]->readI16(_id);
  }

  int32_t readI32(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readI32(_id);
    }
    return ifaces_[i]->readI32(_id);
  }

  int64_t readI64(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readI64(_id);
    }
    return ifaces_[i]->readI64(_id);
  }

  double readDouble(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readDouble(_id);
    }
    return ifaces_[i]->readDouble(_id);
  }

  void readString(std::string& _return, const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readString(_return, _id);
    }
    ifaces_[i]->readString(_return, _id);
    return;
  }

  bool writeId(const std::string& _id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->writeId(_id);
    }
    return ifaces_[i]->writeId(_id);
  }

  void readId(std::vector<std::string> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->readId(_return);
    }
    ifaces_[i]->readId(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TransferServiceConcurrentClient : virtual public TransferServiceIf {
 public:
  TransferServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TransferServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void writeMessage(std::string& _return, const Message& _v);
  int32_t send_writeMessage(const Message& _v);
  void recv_writeMessage(std::string& _return, const int32_t seqid);
  void writeBool(std::string& _return, const std::string& _id, const bool _v);
  int32_t send_writeBool(const std::string& _id, const bool _v);
  void recv_writeBool(std::string& _return, const int32_t seqid);
  void writeI16(std::string& _return, const std::string& _id, const int16_t _v);
  int32_t send_writeI16(const std::string& _id, const int16_t _v);
  void recv_writeI16(std::string& _return, const int32_t seqid);
  void writeI32(std::string& _return, const std::string& _id, const int32_t _v);
  int32_t send_writeI32(const std::string& _id, const int32_t _v);
  void recv_writeI32(std::string& _return, const int32_t seqid);
  void writeI64(std::string& _return, const std::string& _id, const int64_t _v);
  int32_t send_writeI64(const std::string& _id, const int64_t _v);
  void recv_writeI64(std::string& _return, const int32_t seqid);
  void writeDouble(std::string& _return, const std::string& _id, const double _v);
  int32_t send_writeDouble(const std::string& _id, const double _v);
  void recv_writeDouble(std::string& _return, const int32_t seqid);
  void writeString(std::string& _return, const std::string& _id, const std::string& _v);
  int32_t send_writeString(const std::string& _id, const std::string& _v);
  void recv_writeString(std::string& _return, const int32_t seqid);
  void readMessage(Message& _return, const std::string& _id);
  int32_t send_readMessage(const std::string& _id);
  void recv_readMessage(Message& _return, const int32_t seqid);
  bool readBool(const std::string& _id);
  int32_t send_readBool(const std::string& _id);
  bool recv_readBool(const int32_t seqid);
  int16_t readI16(const std::string& _id);
  int32_t send_readI16(const std::string& _id);
  int16_t recv_readI16(const int32_t seqid);
  int32_t readI32(const std::string& _id);
  int32_t send_readI32(const std::string& _id);
  int32_t recv_readI32(const int32_t seqid);
  int64_t readI64(const std::string& _id);
  int32_t send_readI64(const std::string& _id);
  int64_t recv_readI64(const int32_t seqid);
  double readDouble(const std::string& _id);
  int32_t send_readDouble(const std::string& _id);
  double recv_readDouble(const int32_t seqid);
  void readString(std::string& _return, const std::string& _id);
  int32_t send_readString(const std::string& _id);
  void recv_readString(std::string& _return, const int32_t seqid);
  bool writeId(const std::string& _id);
  int32_t send_writeId(const std::string& _id);
  bool recv_writeId(const int32_t seqid);
  void readId(std::vector<std::string> & _return);
  int32_t send_readId();
  void recv_readId(std::vector<std::string> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
