/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "messenger_constants.h"

namespace thrift_gen {

const messengerConstants g_messenger_constants;

messengerConstants::messengerConstants() {
}

} // namespace

