/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef messenger_TYPES_H
#define messenger_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace thrift_gen_messenger {

class Message;

typedef struct _Message__isset {
  _Message__isset() : _receiver_id(false), _subject(false), _sequence_no(false), _total_count(false), _list_bool(false), _list_i16(false), _list_i32(false), _list_i64(false), _list_double(false), _list_string(false), _binary(false), _payload(false) {}
  bool _receiver_id :1;
  bool _subject :1;
  bool _sequence_no :1;
  bool _total_count :1;
  bool _list_bool :1;
  bool _list_i16 :1;
  bool _list_i32 :1;
  bool _list_i64 :1;
  bool _list_double :1;
  bool _list_string :1;
  bool _binary :1;
  bool _payload :1;
} _Message__isset;

class Message : public virtual ::apache::thrift::TBase {
 public:

  Message(const Message&);
  Message& operator=(const Message&);
  Message() : _timestamp(), _sender_id(), _receiver_id(), _subject(), _sequence_no(0), _total_count(0), _binary(), _payload() {
  }

  virtual ~Message() throw();
  std::string _timestamp;
  std::string _sender_id;
  std::string _receiver_id;
  std::string _subject;
  int64_t _sequence_no;
  int64_t _total_count;
  std::vector<bool>  _list_bool;
  std::vector<int16_t>  _list_i16;
  std::vector<int32_t>  _list_i32;
  std::vector<int64_t>  _list_i64;
  std::vector<double>  _list_double;
  std::vector<std::string>  _list_string;
  std::string _binary;
  std::string _payload;

  _Message__isset __isset;

  void __set__timestamp(const std::string& val);

  void __set__sender_id(const std::string& val);

  void __set__receiver_id(const std::string& val);

  void __set__subject(const std::string& val);

  void __set__sequence_no(const int64_t val);

  void __set__total_count(const int64_t val);

  void __set__list_bool(const std::vector<bool> & val);

  void __set__list_i16(const std::vector<int16_t> & val);

  void __set__list_i32(const std::vector<int32_t> & val);

  void __set__list_i64(const std::vector<int64_t> & val);

  void __set__list_double(const std::vector<double> & val);

  void __set__list_string(const std::vector<std::string> & val);

  void __set__binary(const std::string& val);

  void __set__payload(const std::string& val);

  bool operator == (const Message & rhs) const
  {
    if (!(_timestamp == rhs._timestamp))
      return false;
    if (!(_sender_id == rhs._sender_id))
      return false;
    if (__isset._receiver_id != rhs.__isset._receiver_id)
      return false;
    else if (__isset._receiver_id && !(_receiver_id == rhs._receiver_id))
      return false;
    if (__isset._subject != rhs.__isset._subject)
      return false;
    else if (__isset._subject && !(_subject == rhs._subject))
      return false;
    if (__isset._sequence_no != rhs.__isset._sequence_no)
      return false;
    else if (__isset._sequence_no && !(_sequence_no == rhs._sequence_no))
      return false;
    if (__isset._total_count != rhs.__isset._total_count)
      return false;
    else if (__isset._total_count && !(_total_count == rhs._total_count))
      return false;
    if (__isset._list_bool != rhs.__isset._list_bool)
      return false;
    else if (__isset._list_bool && !(_list_bool == rhs._list_bool))
      return false;
    if (__isset._list_i16 != rhs.__isset._list_i16)
      return false;
    else if (__isset._list_i16 && !(_list_i16 == rhs._list_i16))
      return false;
    if (__isset._list_i32 != rhs.__isset._list_i32)
      return false;
    else if (__isset._list_i32 && !(_list_i32 == rhs._list_i32))
      return false;
    if (__isset._list_i64 != rhs.__isset._list_i64)
      return false;
    else if (__isset._list_i64 && !(_list_i64 == rhs._list_i64))
      return false;
    if (__isset._list_double != rhs.__isset._list_double)
      return false;
    else if (__isset._list_double && !(_list_double == rhs._list_double))
      return false;
    if (__isset._list_string != rhs.__isset._list_string)
      return false;
    else if (__isset._list_string && !(_list_string == rhs._list_string))
      return false;
    if (__isset._binary != rhs.__isset._binary)
      return false;
    else if (__isset._binary && !(_binary == rhs._binary))
      return false;
    if (__isset._payload != rhs.__isset._payload)
      return false;
    else if (__isset._payload && !(_payload == rhs._payload))
      return false;
    return true;
  }
  bool operator != (const Message &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Message &a, Message &b);

std::ostream& operator<<(std::ostream& out, const Message& obj);

} // namespace

#endif
